#!/usr/bin/env bash
#resolve localhost to 127.0.0.2 and fb to 8.8.8.8
echo -e "8.8.8.8\tfacebook.com" >> //etc/hosts
cp /etc/hosts ~/hosts.new
sed -i -e 's|127.*host|127.0.0.2\tlocalhost|g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts